# Generated by Django 2.2.19 on 2021-03-02 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fact',
            fields=[
                ('fact_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('discription', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='solution',
            fields=[
                ('sol_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('discription', models.CharField(max_length=300)),
                ('fact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fact')),
            ],
        ),
    ]
